import { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: {
    // this one if the fallback, incas any component doesnt hve a title meta
    default: "NextJs tutorail -codevolution",
    // so tothers can use this in continuation and if u dont want otheers to use this in continuation instead of title use absolute for them
    // if it isnt there, it will just be about
    template: "%s |codevolution",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="bg-yellow-500">header</header>
        {children}
        <footer className="bg-green-500">footer</footer>
      </body>
    </html>
  );
}
